% % flex_setPathList %
%
%PURPOSE: To set up the paths to run the code.
%AUTHORS: AC Kwan, 170505.
%

data_dir = '/Users/alexkwan/Desktop/ongoing data analysis/siniscalchi2019/';
code_dir = '/Users/alexkwan/Desktop/ongoing data analysis/siniscalchi2019/matlab flexibility';

% add the paths needed for this code
path_list = {...
    code_dir;...
    fullfile(code_dir,'common functions');...
    fullfile(code_dir,'common functions','cbrewer');...
    fullfile(code_dir,'flex exp lists');...
    fullfile(code_dir,'flex behavior');...
    fullfile(code_dir,'flex fluo');...
    };
addpath(path_list{:});