function blockMask = flex_getBlockMask( x, blocks )
% % getTrialMasks %
%PURPOSE:   For the x-th block, returns the appropriate mask
%AUTHORS:   AC Kwan 170517
%
%INPUT ARGUMENTS
%   trialData:  Structure generated by flex_getSessionData()
%   blocks:     Structure generated by flex_getBlockData()
%
%OUTPUT VARIABLES
%   trials:     Structure containing these fields, each a logical mask
%               indicating whether trial(idx) is of the corresponding subset, e.g.,
%               response==left or cue==upsweep.

nTrials = sum(blocks.nTrials);

blockMask = false(nTrials,1);                   %Create mask for block(x)
firstTrial = blocks.firstTrial(x);
n = blocks.nTrials(x);
blockMask(firstTrial:firstTrial+n-1) = true;
