function [ blocks ] = flex_getMoreBlockData( blocks, trials )
% % getMoreBlockData %
%PURPOSE: Retrieve block and trial data specific to the flexibility task,
%         particularly those known only after running flex_getTrialMasks
%AUTHOSR: MJ Siniscalchi 161212.
%         modified by AC Kwan 170515
%
%INPUT ARGUMENTS
%   blocks:     structure generated by calling flex_getBlockData().
%   trials:     structure generated by calling flex_getTrialMasks().
%
%OUTPUT VARIABLES
%   blocks:         Fields: 
%                   {firstTrial, nTrials, ...
%                   hit, err_p, err_o, miss, ...
%                   contingType, ruleType}. 

nTrials = sum(blocks.nTrials);

%% can only estimate certain statistics (e.g., perseverative errors) after getting trialMask
fields = {'hit' 'err_p' 'err_o' 'miss'};
for i = 1:numel(fields)
    trialMask = trials.(fields{i});

    edges = [blocks.firstTrial; nTrials+1]; 
    counts = histc(find(trialMask),edges); %count number of each outcome in each block
    counts = counts(1:end-1);              %last value can be dropped; it is for count(x>=edges(end))

    blocks.(fields{i})   = counts; 
end

end




