function combinedMask = getAnyMask( trials, fieldNames )
% % geMask %
%PURPOSE:   Get trial mask defined by OR operation of unlimited trial conditions
%AUTHORS:   MJ Siniscalchi, 170113
%
%INPUT ARGUMENTS
%   trials:         structure generated by flex_getTrialMask()
%   fieldNames:     the field names involved
%
%OUTPUT ARGUMENTS
%   combinedMask:   mask where all fields are satisfied, i.e. an AND operation

temp = [];
for i = 1:length(fieldNames)
    temp = [temp trials.(fieldNames{i})]; %trialMasks as columns of array
end
combinedMask = any(temp,2); %true if any element is non-zero

end

