function plot_session_beh_horz(trials,blocks,tlabel)
% % plot_session_beh_horz %
%PURPOSE:   Plot discrim/flexibility task performance, horizontal view
%AUTHORS:   AC Kwan 170515
%
%INPUT ARGUMENTS
%   trials:       Structure generated by flex_getTrialMasks().
%   blocks:       Structure generated by flex_getBlockData().
%   tlabel:       Text to put as title of the plot

%%
nTrials=sum(blocks.nTrials);

figure; 

subplot(2,1,1); hold on;
% color-code the rule blocks
if numel(blocks.firstTrial)>1   %if there are switches
    for jj=1:numel(blocks.firstTrial)
        if jj==numel(blocks.firstTrial)
            x1=blocks.firstTrial(jj)-0.5; x2=nTrials; y1=-4; y2=4;
        else
            x1=blocks.firstTrial(jj)-0.5; x2=blocks.firstTrial(jj+1)-0.5; y1=-4; y2=4;
        end
        if strcmp(blocks.contingType{jj},'Sound')
            fill([x1 x1 x2 x2],[y1 y2 y2 y1],[1 1 1]);
        elseif strcmp(blocks.contingType{jj},'ActionL')
            fill([x1 x1 x2 x2],[y1 y2 y2 y1],[1 0.8 0.8]);
        elseif strcmp(blocks.contingType{jj},'ActionR')
            fill([x1 x1 x2 x2],[y1 y2 y2 y1],[0.8 0.8 1]);
        elseif strcmp(blocks.contingType{jj},'Reversal')
            fill([x1 x1 x2 x2],[y1 y2 y2 y1],[0.8 1 0.8]);
        end
        plot((blocks.firstTrial(jj)-0.5)*[1 1],[-4 4],'Color',[0.5 0.5 0.5],'LineWidth',1);
    end
end

% plot the trial outcomes
if sum(trials.doublereward) > 0  %discrim with probabilistic outcomes
    plot(find(trials.hit==1),4*ones(1,sum(trials.hit)),'ko','MarkerSize',10,'LineWidth',2);
    plot(find(trials.doublereward==1),3*ones(1,sum(trials.doublereward)),'ko','MarkerSize',10,'LineWidth',2);
    plot(find(trials.omitreward==1),2*ones(1,sum(trials.omitreward)),'ko','MarkerSize',10,'LineWidth',2);
    plot(find(trials.err==1),1*ones(1,sum(trials.err)),'k^','MarkerSize',10,'LineWidth',2);
    plot(find(trials.miss==1),0*ones(1,sum(trials.miss)),'kx','MarkerSize',10,'LineWidth',2);
    set(gca,'yticklabel',{'Miss' 'Error' 'Omitted' 'Double' 'Single'},'ytick',[0:1:4]);
elseif sum(trials.err_p) > 0  %flexibility task
    plot(find(trials.hit==1),3*ones(1,sum(trials.hit)),'k.','MarkerSize',15,'LineWidth',2);
    plot(find(trials.err_p==1),2*ones(1,sum(trials.err_p)),'ko','MarkerSize',10,'LineWidth',2);
    plot(find(trials.err_o==1),1*ones(1,sum(trials.err_o)),'k^','MarkerSize',10,'LineWidth',2);
    plot(find(trials.miss==1),0*ones(1,sum(trials.miss)),'kx','MarkerSize',10,'LineWidth',2);
    set(gca,'yticklabel',{'Miss' 'O-err' 'P-err' 'Hit'},'ytick',[0:1:3]);
else    %discrim
    plot(find(trials.hit==1),2*ones(1,sum(trials.hit)),'k.','MarkerSize',15,'LineWidth',2);
    plot(find(trials.err==1),1*ones(1,sum(trials.err)),'k^','MarkerSize',10,'LineWidth',2);
    plot(find(trials.miss==1),0*ones(1,sum(trials.miss)),'kx','MarkerSize',10,'LineWidth',2);
    set(gca,'yticklabel',{'Miss' 'Err' 'Hit'},'ytick',[0:1:2]);
end
xlim([0 nTrials+1]);
ylim([-1 5]);
xlabel('Trial');
title({tlabel;'{\color[rgb]{0.5 0.5 0.5}Sound} / {\color[rgb]{1 0.5 0.5}Action-left} / {\color[rgb]{0.5 0.5 1}Action-right} / {\color[rgb]{0.5 1 0.5}Reversal}'});

% plot the stimuli
subplot(6,1,4); hold on;
bar(-1*(trials.upsweep==1),1,'FaceColor','r','EdgeColor','none');
bar((trials.downsweep==1),1,'FaceColor','b','EdgeColor','none');
set(gca,'yticklabel',{'Upsw.','Downsw.'},'ytick',[-1 1]);
ylabel('Stimulus');
xlim([0 nTrials+1]);

% plot the response
subplot(6,1,6); hold on;
bar(-1*(trials.left==1),1,'FaceColor','r','EdgeColor','none');
bar((trials.right==1),1,'FaceColor','b','EdgeColor','none');
set(gca,'yticklabel',{'Left' 'Right'},'ytick',[-1 1]);
ylabel('Response');
xlim([0 nTrials+1]);
xlabel('Trial');

print(gcf,'session_horz','-dpng');    %png format
saveas(gcf,'session_horz', 'fig');
print(gcf,'session_horz','-depsc','-painters');   %eps format

end


