function output = calc_selectivity(input1,input2)
% % calc_selectivity %
%PURPOSE:   Calculate selectivity, based on PSTHs from two conditions
%               Selectivity = (A-B)/(A+B)
%AUTHORS:   AC Kwan 171216
%
%INPUT ARGUMENTS
%   input1:       Structure generated by get_psth(), condition 1, e.g., left choice
%   input2:       Structure generated by get_psth(), condition 2, e.g., right choice
%
%OUTPUT ARGUMENTS
%   output:       Structure containing the analysis results

output.signal=(input1.signal-input2.signal)./(input1.signal+input2.signal);

output.t=input1.t;
output.input1_label = input1.psth_label;
output.input2_label = input2.psth_label;
output.input1_nEvent = input1.nEvent;
output.input2_nEvent = input2.nEvent;

end