function check_imageFrameTimes ( cells, stackInfo, tlabel )
% % check_imageFrameTimes %
%PURPOSE:   Check the synchronization of imaging + behavioral data
%AUTHORS:   AC Kwan 170515
%
%INPUT ARGUMENTS
%   cells:          Structure generated by calc_dFF().
%   stackInfo:      content of the stackInfo.mat file for this imaging session
%   tlabel:         Text to put in the title

%% Make sure the image frame times are reasonable
% Time between frames should be around dt

dt=1/stackInfo.frameRate;

figure;
subplot(2,1,1); hold on;
plot(1:numel(cells.t)-1, diff(cells.t),'k');
xlabel('Frames');
ylabel('Time between frames (s)');
title({tlabel},'interpreter','none');

%if .tiff acquired using ScanImage 5, then the stackInfo contains precise
%times for each frame. Plot to compare with the cells.t (frame times after
%aligning to behavioral logfile trigger times)
if isfield(stackInfo,'frameTime')
    subplot(2,1,2); hold on;
    plot(1:numel(stackInfo.frameTime)-1, diff(stackInfo.frameTime),'k');
    xlabel('Frames');
    ylabel({'Time between frames (s)'});
    title('According to stackInfo.frameTime');
end

print(gcf,'-dpng','check-timing');    %png format
saveas(gcf, 'check-timing', 'fig');

end