function plot_psth_comp(input1,input2,compTime,minNumTrial,tlabel)
% % plot_selectivity %
%PURPOSE:   Scatter plot comparing PSTH or selectivity from two situations
%AUTHORS:   AC Kwan 170515
%
%INPUT ARGUMENTS
%   input1:       Structure generated by calc_psth() or calc_selectivity()
%   input2:       Structure generated by calc_psth() or calc_selectivity()
%   compTime:     Compare the cells based on psth or selectivity value in this time period
%   minNumTrial:  At least this number of trials to be included in analysis
%   tlabel:       Text to put as title of the plot.
%   xtitle:       Text to put as the label for x-axis.

%% Setup
maxY = 1;
minY = -maxY;

t=input1{1}.t;
nCells=numel(input1);   

%get mean value at specified time
tIdx = [max([sum(t<=compTime(1)) 1]):sum(t<=compTime(2))];  %index should start from at least value of 1
for j = 1:nCells
    val1(j) = nanmean(input1{j}.signal(tIdx,1),1);
    val2(j) = nanmean(input2{j}.signal(tIdx,1),1);
    
    input1event1(j) = input1{j}.input1_nEvent(1);
    input1event2(j) = input1{j}.input2_nEvent(1);
    input2event1(j) = input2{j}.input1_nEvent(1);
    input2event2(j) = input2{j}.input2_nEvent(1);
end

%criteria for inclusion into the analysis
crit1 = ~isnan(val1) & ~isnan(val2);
crit2 = (input1event1>=minNumTrial) & (input1event2>=minNumTrial) & (input2event1>=minNumTrial) & (input2event2>=minNumTrial);

crit = crit1 & crit2;

%% scatter plot

figure; subplot(2,2,1); hold on;

plot([0 0],[minY maxY],'k','LineWidth',1);
plot([minY maxY],[0 0],'k','LineWidth',1);
plot(val1(crit),val2(crit),'k.','MarkerSize',10);

xlabel({input1{1}.input1_label;input1{1}.input2_label});
xlim([minY maxY]);
ylabel({input2{1}.input1_label;input2{1}.input2_label});
ylim([minY maxY]);

[temp p] = corrcoef(val1(crit),val2(crit));
title({[tlabel '; n = ' int2str(sum(crit)) ' cells'];['corr coeff=' num2str(temp(2,1)) '; p=' num2str(p(2,1))]});
axis square;

%% cumulative distribution

subplot(2,2,2); hold on;
[fval1,fedges1]=ecdf(abs(val1(crit))); %find cumulative distribution
[fval2,fedges2]=ecdf(abs(val2(crit))); %find cumulative distribution

plot(fedges1,fval1,'k');
plot(fedges2,fval2,'k--');
ylabel('Cumulative distribution');
xlabel('Choice selectivity magnitude');
xlim([0 1]);
ylim([0 1]);
legend({input1{1}.input1_label,input2{1}.input1_label},'location','SouthEast');

p=signrank(abs(val1(crit)),abs(val2(crit)));
title({tlabel;['p=' num2str(p) ' (Wilcoxon signed-rank)']});

end
